#!/usr/bin/env bash

exec >&2 6>&1

mkdir -p /var/tmp/rethinkdb-dump
chown gonano:gonano -R /var/tmp/rethinkdb-dump

/data/bin/rethinkdb dump -f - --temp-dir /var/tmp/rethinkdb-dump >&6

rm -rf /var/tmp/rethinkdb-dump
