#!/usr/bin/env bash

exec 6<&0

mkdir -p /var/tmp/rethinkdb-restore
chown gonano:gonano -R /var/tmp/rethinkdb-restore

/data/bin/rethinkdb restore --force --hard-durability --temp-dir /var/tmp/rethinkdb-restore - <&6

rm -rf /var/tmp/rethinkdb-restore
