#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# pipe the backup into rethinkdb client to restore from backup
directory '/var/tmp/rethinkdb-restore' do
  recursive true
  owner "gonano"
  group "gonano"
end

execute "retrieve backup from server" do
  command "scp -o StrictHostKeyChecking=no #{payload[:warehouse][:host]}:/data/var/db/rethinkdb/#{payload[:warehouse][:backup_id]}.tar.gz /var/tmp/rethinkdb.tar.gz"
end

execute "restore from backup" do
  command "/data/bin/rethinkdb restore --force --hard-durability --temp-dir /var/tmp/rethinkdb-restore /var/tmp/rethinkdb.tar.gz"
  user "gonano"
end

file "/var/tmp/rethinkdb.tar.gz" do
  action :delete
end

directory '/var/tmp/rethinkdb-restore' do
  action :delete
end
